### ISSUE TITLE
Liens "Blame" et "History" ne fonctionnent pas

### ISSUE THREAD

**Issue by targos** [ES-Community/ES-Community.github.io#10]
En bas de chaque article se trouvent 2 liens vers github: 
![image](https://user-images.githubusercontent.com/2352663/62007958-4127b000-b154-11e9-998a-852a3df01a9f.png)

Ils ne fonctionnent pas car le chemin du fichier n'est pas remplacé. Voici à quoi ressemble le lien blame par exemple: `https://github.com/ES-Community/ES-Community.github.io/blame/source/source/%3C%=%20page.source%20%%3E`

**Comment by Purexo** [comment]
Soucis corrigé.
Merci @targos  pour ton œil affuté et @Sebastien-Ahkrin pour ta PR.
